on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    name: "build"
    runs-on: ubuntu-latest
    steps:
    - name: Build and push Docker images
      uses: docker/build-push-action@v1.1.0
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: aquariumbio/pfish
        tag_with_ref: true
        tag_with_sha: true
        add_git_labels: true
